from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    HomeView,
    BrowseView,
    BookCreateView,
    AuthorCreateView,
    BookDetailView,
    CheckoutView,
    ContactSellerView,
    SubscribeView,
    BookEditView,
    BookDeleteView,
    OrderConfirmedView,
    CartView,
    AddToCartView,
    RemoveFromCartView,
    CartCheckoutView,
    CartOrderConfirmedView,
    CartOrderConfirmedSuccessView,
    EsewaSuccessView,
    EsewaFailureView,
    SalesView,
    BestSellersView,
    GenresView,
    AuthorsView,
    WishlistView,
    OrdersView,
    CompleteOrderView,
    SellerCompleteOrderView,
    CancelOrderView,
    AboutView,
    ContactView,
    BlogView,
    MessagesInboxView,
    ConversationMessagesView,
    SendChatMessageView,
    StartConversationView,
)

app_name = "books"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("browse/", BrowseView.as_view(), name="browse"),
    path("sell/", BookCreateView.as_view(), name="sell"),
    path("sell/add-author/", AuthorCreateView.as_view(), name="author_create"),
    path("book/<str:seller>/<slug:slug>/", BookDetailView.as_view(), name="detail"),
    path("book/<str:seller>/<slug:slug>/checkout/", CheckoutView.as_view(), name="checkout"),
    path(
        "book/<str:seller>/<slug:slug>/contact-seller/",
        ContactSellerView.as_view(),
        name="contact_seller",
    ),
    path("subscribe/", SubscribeView.as_view(), name="subscribe"),
    path("book/<str:seller>/<slug:slug>/edit/", BookEditView.as_view(), name="edit"),
    path("book/<str:seller>/<slug:slug>/delete/", BookDeleteView.as_view(), name="delete"),
    path("order/<slug:order_slug>/confirmed/", OrderConfirmedView.as_view(), name="order_confirmed"),
    path("order/<slug:order_slug>/complete/", CompleteOrderView.as_view(), name="order_complete"),
    path("order/<slug:order_slug>/seller-complete/", SellerCompleteOrderView.as_view(), name="order_seller_complete"),
    path("order/<slug:order_slug>/cancel/", CancelOrderView.as_view(), name="order_cancel"),
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/add/<str:seller>/<slug:slug>/", AddToCartView.as_view(), name="add_to_cart"),
    path("cart/remove/<slug:slug>/", RemoveFromCartView.as_view(), name="remove_from_cart"),
    path("cart/checkout/", CartCheckoutView.as_view(), name="cart_checkout"),
    path("cart/order-confirmed/", CartOrderConfirmedView.as_view(), name="cart_order_confirmed"),
    path("cart/order-confirmed/success/", CartOrderConfirmedSuccessView.as_view(), name="cart_order_confirmed_success"),
    path("payment/esewa/success/", EsewaSuccessView.as_view(), name="esewa_success"),
    path("payment/esewa/failure/", EsewaFailureView.as_view(), name="esewa_failure"),
    path("sales/", SalesView.as_view(), name="sales"),
    path("bestsellers/", BestSellersView.as_view(), name="bestsellers"),
    path("genres/", GenresView.as_view(), name="genres"),
    path("authors/", AuthorsView.as_view(), name="authors"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("orders/", OrdersView.as_view(), name="orders"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("blog/", BlogView.as_view(), name="blog"),
    path("messages/", MessagesInboxView.as_view(), name="messages_inbox"),
    path("messages/start/", StartConversationView.as_view(), name="start_conversation"),
    path("messages/<int:pk>/messages/", ConversationMessagesView.as_view(), name="conversation_messages"),
    path("messages/<int:pk>/send/", SendChatMessageView.as_view(), name="send_chat_message"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)