# Generated by Django 5.0.14 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookimage",
            name="unique_image_order_per_book",
        ),
        migrations.AlterField(
            model_name="bookimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("cover", "Cover"),
                    ("back", "Back Cover"),
                    ("spine", "Spine"),
                    ("condition", "Condition Photo"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
