# Generated by Django 5.0.14 on 2026-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non_fiction", "Non-Fiction"),
                    ("textbook", "Textbook"),
                    ("science", "Science"),
                    ("technology", "Technology"),
                    ("history", "History"),
                    ("biography", "Biography"),
                    ("self_help", "Self Help"),
                    ("business", "Business"),
                    ("children", "Children"),
                    ("comics", "Comics & Manga"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
