# Generated by Django 5.0.14 on 2026-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("cover", "Cover"),
                    ("back", "Back Cover"),
                    ("spine", "Spine"),
                    ("condition", "Condition Photo"),
                    ("other", "Other"),
                ],
                default="cover",
                max_length=20,
            ),
        ),
    ]
