# Generated by Django 5.0.14 on 2026-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_bookimage_image_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookimage",
            name="image",
            field=models.ImageField(upload_to="book_images/"),
        ),
    ]
