# Generated by Django 5.0.14 on 2026-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_bookimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
