# Generated by Django 5.0.14 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_cartitem_cartitem_unique_cart_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="num_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
