# Generated by Django 5.0.14 on 2026-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_book_num_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
