# Generated by Django 5.0.14 on 2026-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_messagereply"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="esewa_ref_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
