# Generated by Django 5.0.14 on 2026-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_transaction_esewa_ref_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("esewa", "eSewa"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("order_request", "Order Requested"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="order_request",
                max_length=20,
            ),
        ),
    ]
