# Generated by Django 5.0.14 on 2026-05-29 19:39

from django.conf import settings
from django.db import migrations, models, transaction


def dedupe_conversations(apps, schema_editor):
    Conversation = apps.get_model('books', 'Conversation')
    ChatMessage = apps.get_model('books', 'ChatMessage')
    db_alias = schema_editor.connection.alias

    seen = {}
    qs = Conversation.objects.using(db_alias).all().order_by('id')
    for conv in qs:
        key = (conv.buyer_id, conv.seller_id)
        if key not in seen:
            seen[key] = conv
            continue

        keeper = seen[key]
        # move related chat messages to the keeper
        ChatMessage.objects.using(db_alias).filter(conversation=conv).update(conversation=keeper)

        # preserve book if keeper has none
        if not keeper.book_id and conv.book_id:
            keeper.book_id = conv.book_id

        # keep the most recent last_message_at
        if conv.last_message_at and (not keeper.last_message_at or conv.last_message_at > keeper.last_message_at):
            keeper.last_message_at = conv.last_message_at

        keeper.save(update_fields=['book_id', 'last_message_at'])
        # remove the duplicate conversation
        Conversation.objects.using(db_alias).filter(pk=conv.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_conversation_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_conversation_per_book",
        ),
        migrations.RunPython(dedupe_conversations, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("buyer", "seller"), name="unique_conversation_per_pair"
            ),
        ),
    ]
