# Generated by Django 5.0.14 on 2026-05-29 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_remove_conversation_unique_conversation_per_book_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_conversation_per_pair",
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("buyer", "seller", "book"), name="unique_conversation_per_book"
            ),
        ),
    ]
