# Generated by Django 5.0.14 on 2026-05-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_conversations(apps, schema_editor):
    Conversation = apps.get_model('books', 'Conversation')
    ChatMessage = apps.get_model('books', 'ChatMessage')
    db_alias = schema_editor.connection.alias

    seen = {}
    for conv in Conversation.objects.using(db_alias).all().order_by('id'):
        key = (conv.buyer_id, conv.seller_id)
        if key not in seen:
            seen[key] = conv
            continue

        keeper = seen[key]

        ChatMessage.objects.using(db_alias).filter(conversation=conv).update(conversation=keeper)

        if not keeper.book_id and conv.book_id:
            keeper.book_id = conv.book_id

        if conv.last_message_at and (
            not keeper.last_message_at or conv.last_message_at > keeper.last_message_at
        ):
            keeper.last_message_at = conv.last_message_at

        keeper.save(update_fields=['book_id', 'last_message_at'])
        conv.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_remove_conversation_unique_conversation_per_pair_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_conversation_per_book",
        ),
        migrations.RunPython(dedupe_conversations, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="chatmessage",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="books.book",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("buyer", "seller"), name="unique_conversation_per_pair"
            ),
        ),
    ]