# Generated by Django 5.0.14 on 2026-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_remove_conversation_unique_conversation_per_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="esewa_attempt_uuid",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
